source 'https://rubygems.org'

gem 'sinatra-activerecord'
gem 'activesupport'
gem "bundler"
gem 'pg'
gem 'puma'
gem 'rake'
gem 'pry'
gem 'redis-sinatra'
gem 'redis'
gem 'redis-namespace'
gem 'redis-rack-cache'
gem 'coinbase'
gem 'slim'
gem 'sinatra-json', '~> 0.1.0'
# gem 'redis-throttle', git: 'git://github.com/lelylan/redis-throttle.git'